export default {
  "eons": {
    "phanerozoic": { "name": "Phanerozoic", "min": 0, "min_sigma": 0, "max": 542, "max_sigma": 1 },
    "proterozoic": { "name": "Proterozoic", "min": 542, "min_sigma": 1, "max": 2500 },
    "archean":     { "name": "Archean",     "min": 2500, "max": 4555 }
  },
  "eras": {
    "cenozoic": { "name": "Cenozoic", "min": 0, "min_sigma": 0, "max": 65.5, "max_sigma": .3},
    "mesozoic": { "name": "Mesozoic", "min": 65.5, "min_sigma": .3, "max": 251, "max_sigma": .4},
    "paleozoic": { "name": "Paleozoic", "min": 251, "min_sigma": .4, "max": 542, "max_sigma": 1},
    "neoproterozoic": { "name": "Neoproterozoic", "min": 542, "min_sigma": 1, "max": 1000 },
    "mesoproterozoic": { "name": "Mesoproterozoic", "min": 1000, "max": 1600 },
    "paleoproterozoic": { "name": "Paleoproterozoic", "min": 1600, "max": 2500 },
    "neoarchean": { "name": "Neoarchean", "min": 2500, "max": 2800 },
    "mesoarchean": { "name": "Mesoarchean", "min": 2800, "max": 3200 },
    "paleoarchean": { "name": "Paleoarchean", "min": 3200, "max": 3600 },
    "eoarchean": { "name": "Eoarchean", "min": 3600, "max": 4555 }
  },
  "periods": {
    "neogene": { "name": "Neogene", "min": 0, "min_sigma": 0, "max": 23.03, "max_sigma": 0},
    "paleogene": { "name": "Paleogene", "min": 23.03, "min_sigma": 0, "max": 65.5, "max_sigma": .3},
    "cretaceous": { "name": "Cretaceous", "min": 65.5, "min_sigma": .3, "max": 145.5, "max_sigma": 4},
    "jurassic": { "name": "Jurassic", "min": 145.5, "min_sigma": 4, "max": 199.6, "max_sigma": .6},
    "triassic": { "name": "Triassic", "min": 199.6, "min_sigma": .6, "max": 251, "max_sigma": .4},
    "permian": { "name": "Permian", "min": 251, "min_sigma": .4, "max": 299, "max_sigma": .8},
    "carboniferous": { "name": "Carboniferous", "min": 299, "min_sigma": .8, "max": 359.2, "max_sigma": 2.5},
    "devonian": { "name": "Devonian", "min": 359.2, "min_sigma": 2.5, "max": 416, "max_sigma": 2.8},
    "silurian": { "name": "Silurian", "min": 416, "min_sigma": 2.8, "max": 443.7, "max_sigma": 1.5},
    "ordovician": { "name": "Ordovician", "min": 443.7, "min_sigma": 1.5, "max": 488.3, "max_sigma": 1.7},
    "cambrian": { "name": "Cambrian", "min": 488.3, "min_sigma": 1.7, "max": 542, "max_sigma": 1},
    "ediacaran": { "name": "Ediacaran", "min": 542, "min_sigma": 1, "max": 620 },
    "cryogenian": { "name": "Cryogenian", "min": 620, "max": 850 },
    "tonian": { "name": "Tonian", "min": 850, "max": 1000 },
    "stenian": { "name": "Stenian", "min": 1000, "max": 1200 },
    "ectasian": { "name": "Ectasian", "min": 1200, "max": 1400 },
    "calymmian": { "name": "Calymmian", "min": 1400, "max": 1600 },
    "statherian": { "name": "Statherian", "min": 1600, "max": 1800 },
    "orosirian": { "name": "Orosirian", "min": 1800, "max": 2050 },
    "rhyacian": { "name": "Rhyacian", "min": 2050, "max": 2300 },
    "siderian": { "name": "Siderian", "min": 2300, "max": 2500 }
  },
  "epochs": {
    "holocene": { "name": "Holocene", "min": 0, "min_sigma": 0, "max": .0115, "max_sigma": 0},
    "pleistocene": { "name": "Pleistocene", "min": .0115, "min_sigma": 0, "max": 1.806, "max_sigma": 0},
    "pliocene": { "name": "Pliocene", "min": 1.806, "min_sigma": 0, "max": 5.333, "max_sigma": 0},
    "miocene": { "name": "Miocene", "min": 5.333, "min_sigma": 0, "max": 23.03, "max_sigma": 0},
    "oligocene": { "name": "Oligocene", "min": 23.03, "min_sigma": 0, "max": 33.9, "max_sigma": .1},
    "eocene": { "name": "Eocene", "min": 33.9, "min_sigma": .1, "max": 55.8, "max_sigma": .2},
    "paleocene": { "name": "Paleocene", "min": 55.8, "min_sigma": .2, "max": 65.5, "max_sigma": .3},
    "late cretaceous": { "name": "Late Cretaceous", "min": 65.5, "min_sigma": .3, "max": 99.6, "max_sigma": .9},
    "early cretaceous": { "name": "Early Cretaceous", "min": 99.6, "min_sigma": .9, "max": 145.5, "max_sigma": 4},
    "late jurassic": { "name": "Late Jurassic", "min": 145.5, "min_sigma": 4, "max": 161.2, "max_sigma": 4},
    "middle jurassic": { "name": "Middle Jurassic", "min": 161.2, "min_sigma": 4, "max": 175.6, "max_sigma": 2},
    "early jurassic": { "name": "Early Jurassic", "min": 175.6, "min_sigma": 2, "max": 199.6, "max_sigma": .6},
    "late triassic": { "name": "Late Triassic", "min": 199.6, "min_sigma": .6, "max": 228, "max_sigma": 2},
    "middle triassic": { "name": "Middle Triassic", "min": 228, "min_sigma": 2, "max": 245, "max_sigma": 1.5},
    "early triassic": { "name": "Early Triassic", "min": 245, "min_sigma": 1.5, "max": 251, "max_sigma": .4},
    "lopingian": { "name": "Lopingian", "min": 251, "min_sigma": .4, "max": 260.4, "max_sigma": .7},
    "guadalupian": { "name": "Guadalupian", "min": 260.4, "min_sigma": .7, "max": 270.6, "max_sigma": .7},
    "cisuralian": { "name": "Cisuralian", "min": 270.6, "min_sigma": .7, "max": 299, "max_sigma": .8},
    "pennsylvanian": { "name": "Pennsylvanian", "min": 299, "min_sigma": .8, "max": 318.1, "max_sigma": 1.3},
    "mississippian": { "name": "Mississippian", "min": 318.1, "min_sigma": 1.3, "max": 359.2, "max_sigma": 2.5},
    "late devonian": { "name": "Late Devonian", "min": 359.2, "min_sigma": 2.5, "max": 385.3, "max_sigma": 2.6},
    "middle devonian": { "name": "Middle Devonian", "min": 385.3, "min_sigma": 2.6, "max": 397.5, "max_sigma": 2.7},
    "early devonian": { "name": "Early Devonian", "min": 397.5, "min_sigma": 2.7, "max": 416, "max_sigma": 2.8},
    "pridoli": { "name": "Pridoli", "min": 416, "min_sigma": 2.8, "max": 418.7, "max_sigma": 2.7},
    "ludlow": { "name": "Ludlow", "min": 418.7, "min_sigma": 2.7, "max": 422.9, "max_sigma": 2.5},
    "wenlock": { "name": "Wenlock", "min": 422.9, "min_sigma": 2.5, "max": 428.2, "max_sigma": 2.3},
    "llandovery": { "name": "Llandovery", "min": 428.2, "min_sigma": 2.3, "max": 443.7, "max_sigma": 1.5},
    "late ordovician": { "name": "Late Ordovician", "min": 443.7, "min_sigma": 1.5, "max": 460.9, "max_sigma": 1.6},
    "middle ordovician": { "name": "Middle Ordovician", "min": 460.9, "min_sigma": 1.6, "max": 471.8, "max_sigma": 1.6},
    "early ordovician": { "name": "Early Ordovician", "min": 471.8, "min_sigma": 1.6, "max": 488.3, "max_sigma": 1.7},
    "furongian": { "name": "Furongian", "min": 488.3, "min_sigma": 1.7, "max": 501, "max_sigma": 2},
    "middle cambrian": { "name": "Middle Cambrian", "min": 501, "min_sigma": 2, "max": 513, "max_sigma": 2},
    "early cambrian": { "name": "Early Cambrian", "min": 513, "min_sigma": 2, "max": 542, "max_sigma": 1}
  },
  "stages": {
    "late pleistocene": { "name": "Late Pleistocene", "min": .0115, "min_sigma": 0, "max": .126, "max_sigma": 0},
    "middle pleistocene": { "name": "Middle Pleistocene", "min": .126, "min_sigma": 0, "max": .781, "max_sigma": 0},
    "early pleistocene": { "name": "Early Pleistocene", "min": .781, "min_sigma": 0, "max": 1.806, "max_sigma": 0},
    "gelasian": { "name": "Gelasian", "min": 1.806, "min_sigma": 0, "max": 2.588, "max_sigma": 0},
    "piacenzian": { "name": "Piacenzian", "min": 2.588, "min_sigma": 0, "max": 3.6, "max_sigma": 0},
    "zanclean": { "name": "Zanclean", "min": 3.6, "min_sigma": 0, "max": 5.333, "max_sigma": 0},
    "messinian": { "name": "Messinian", "min": 5.333, "min_sigma": 0, "max": 7.248, "max_sigma": 0},
    "tortonian": { "name": "Tortonian", "min": 7.248, "min_sigma": 0, "max": 11.608, "max_sigma": 0},
    "serravillian": { "name": "Serravillian", "min": 11.608, "min_sigma": 0, "max": 13.64, "max_sigma": 0},
    "langhian": { "name": "Langhian", "min": 13.64, "min_sigma": 0, "max": 15.97, "max_sigma": 0},
    "burdigalian": { "name": "Burdigalian", "min": 15.97, "min_sigma": 0, "max": 20.43, "max_sigma": 0},
    "aquitanian": { "name": "Aquitanian", "min": 20.43, "min_sigma": 0, "max": 23.03, "max_sigma": 0},
    "chattian": { "name": "Chattian", "min": 23.03, "min_sigma": 0, "max": 28.4, "max_sigma": .1},
    "rupelian": { "name": "Rupelian", "min": 28.4, "min_sigma": .1, "max": 33.9, "max_sigma": .1},
    "priabonian": { "name": "Priabonian", "min": 33.9, "min_sigma": .1, "max": 37.2, "max_sigma": .1},
    "bartonian": { "name": "Bartonian", "min": 37.2, "min_sigma": .1, "max": 40.4, "max_sigma": .2},
    "lutetian": { "name": "Lutetian", "min": 40.4, "min_sigma": .2, "max": 48.6, "max_sigma": .2},
    "ypresian": { "name": "Ypresian", "min": 48.6, "min_sigma": .2, "max": 55.8, "max_sigma": .2},
    "thanetian": { "name": "Thanetian", "min": 55.8, "min_sigma": .2, "max": 58.7, "max_sigma": .2},
    "selandian": { "name": "Selandian", "min": 58.7, "min_sigma": .2, "max": 61.7, "max_sigma": .2},
    "danian": { "name": "Danian", "min": 61.7, "min_sigma": .2, "max": 65.5, "max_sigma": .3},
    "maastrichtian": { "name": "Maastrichtian", "min": 65.5, "min_sigma": .3, "max": 70.6, "max_sigma": .6},
    "campanian": { "name": "Campanian", "min": 70.6, "min_sigma": .6, "max": 83.5, "max_sigma": .7},
    "santonian": { "name": "Santonian", "min": 83.5, "min_sigma": .7, "max": 85.9, "max_sigma": .7},
    "coniacian": { "name": "Coniacian", "min": 85.9, "min_sigma": .7, "max": 89.3, "max_sigma": 1},
    "turonian": { "name": "Turonian", "min": 89.3, "min_sigma": 1, "max": 93.6, "max_sigma": .8},
    "cenomanian": { "name": "Cenomanian", "min": 93.6, "min_sigma": .8, "max": 99.6, "max_sigma": .9},
    "albian": { "name": "Albian", "min": 99.6, "min_sigma": .9, "max": 112, "max_sigma": 1},
    "aptian": { "name": "Aptian", "min": 112, "min_sigma": 1, "max": 125, "max_sigma": 1},
    "barremian": { "name": "Barremian", "min": 125, "min_sigma": 1, "max": 130, "max_sigma": 1.5},
    "hauterivian": { "name": "Hauterivian", "min": 130, "min_sigma": 1.5, "max": 136.4, "max_sigma": 2},
    "valanginian": { "name": "Valanginian", "min": 136.4, "min_sigma": 2, "max": 140.2, "max_sigma": 3},
    "berriasian": { "name": "Berriasian", "min": 140.2, "min_sigma": 3, "max": 145.5, "max_sigma": 4},
    "tithonian": { "name": "Tithonian", "min": 145.5, "min_sigma": 4, "max": 150.8, "max_sigma": 4},
    "kimmeridgian": { "name": "Kimmeridgian", "min": 150.8, "min_sigma": 4, "max": 155.7, "max_sigma": 4},
    "oxfordian": { "name": "Oxfordian", "min": 155.7, "min_sigma": 4, "max": 161.2, "max_sigma": 4},
    "callovian": { "name": "Callovian", "min": 161.2, "min_sigma": 4, "max": 164.7, "max_sigma": 4},
    "bathorian": { "name": "Bathorian", "min": 164.7, "min_sigma": 4, "max": 167.7, "max_sigma": 3.5},
    "bajocian": { "name": "Bajocian", "min": 167.7, "min_sigma": 3.5, "max": 171.6, "max_sigma": 3},
    "aalenian": { "name": "Aalenian", "min": 171.6, "min_sigma": 3, "max": 175.6, "max_sigma": 2},
    "toarcian": { "name": "Toarcian", "min": 175.6, "min_sigma": 2, "max": 183, "max_sigma": 1.5},
    "pliensbachian": { "name": "Pliensbachian", "min": 183, "min_sigma": 1.5, "max": 189.6, "max_sigma": 1.5},
    "sinemurian": { "name": "Sinemurian", "min": 189.6, "min_sigma": 1.5, "max": 196.5, "max_sigma": 1},
    "hettangian": { "name": "Hettangian", "min": 196.5, "min_sigma": 1, "max": 199.6, "max_sigma": .6},
    "rhaetian": { "name": "Rhaetian", "min": 199.6, "min_sigma": .6, "max": 203.3, "max_sigma": 1.5},
    "norian": { "name": "Norian", "min": 203.3, "min_sigma": 1.5, "max": 216.5, "max_sigma": 2},
    "carnian": { "name": "Carnian", "min": 216.5, "min_sigma": 2, "max": 228, "max_sigma": 2},
    "ladinian": { "name": "Ladinian", "min": 228, "min_sigma": 2, "max": 237, "max_sigma": 2},
    "anisian": { "name": "Anisian", "min": 237, "min_sigma": 2, "max": 245, "max_sigma": 1.5},
    "olenekian": { "name": "Olenekian", "min": 245, "min_sigma": 1.5, "max": 249.7, "max_sigma": .7},
    "induan": { "name": "Induan", "min": 249.7, "min_sigma": .7, "max": 251, "max_sigma": .4},
    "changhsingian": { "name": "Changhsingian", "min": 251, "min_sigma": .4, "max": 253.8, "max_sigma": .7},
    "wuchiapingian": { "name": "Wuchiapingian", "min": 253.8, "min_sigma": .7, "max": 260.4, "max_sigma": .7},
    "capitanian": { "name": "Capitanian", "min": 260.4, "min_sigma": .7, "max": 265.8, "max_sigma": .7},
    "wordian": { "name": "Wordian", "min": 265.8, "min_sigma": .7, "max": 268, "max_sigma": .7},
    "roadian": { "name": "Roadian", "min": 268, "min_sigma": .7, "max": 270.6, "max_sigma": .7},
    "kungurian": { "name": "Kungurian", "min": 270.6, "min_sigma": .7, "max": 275.6, "max_sigma": .7},
    "artinskian": { "name": "Artinskian", "min": 275.6, "min_sigma": .7, "max": 284.4, "max_sigma": .7},
    "sakmarian": { "name": "Sakmarian", "min": 284.4, "min_sigma": .7, "max": 294.6, "max_sigma": .8},
    "asselian": { "name": "Asselian", "min": 294.6, "min_sigma": .8, "max": 299, "max_sigma": .8},
    "gzhelan": { "name": "Gzhelan", "min": 299, "min_sigma": .8, "max": 303.9, "max_sigma": .9},
    "kasimovian": { "name": "Kasimovian", "min": 303.9, "min_sigma": .9, "max": 306.5, "max_sigma": 1},
    "moscovian": { "name": "Moscovian", "min": 306.5, "min_sigma": 1, "max": 311.7, "max_sigma": 1.1},
    "bashkirian": { "name": "Bashkirian", "min": 311.7, "min_sigma": 1.1, "max": 318.1, "max_sigma": 1.3},
    "serpukhovian": { "name": "Serpukhovian", "min": 318.1, "min_sigma": 1.3, "max": 326.4, "max_sigma": 1.6},
    "visean": { "name": "Visean", "min": 326.4, "min_sigma": 1.6, "max": 345.3, "max_sigma": 2.1},
    "tournaisian": { "name": "Tournaisian", "min": 345.3, "min_sigma": 2.1, "max": 359.2, "max_sigma": 2.5},
    "famennian": { "name": "Famennian", "min": 359.2, "min_sigma": 2.5, "max": 374.5, "max_sigma": 2.6},
    "frasnian": { "name": "Frasnian", "min": 374.5, "min_sigma": 2.6, "max": 385.3, "max_sigma": 2.6},
    "givetian": { "name": "Givetian", "min": 385.3, "min_sigma": 2.6, "max": 391.8, "max_sigma": 2.7},
    "eifelian": { "name": "Eifelian", "min": 391.8, "min_sigma": 2.7, "max": 397.5, "max_sigma": 2.7},
    "emsian": { "name": "Emsian", "min": 397.5, "min_sigma": 2.7, "max": 407, "max_sigma": 2.8},
    "pragian": { "name": "Pragian", "min": 407, "min_sigma": 2.8, "max": 411.2, "max_sigma": 2.8},
    "lochkovian": { "name": "Lochkovian", "min": 411.2, "min_sigma": 2.8, "max": 416, "max_sigma": 2.8},
    "ludfordian": { "name": "Ludfordian", "min": 418.7, "min_sigma": 2.7, "max": 421.3, "max_sigma": 2.6},
    "gorstian": { "name": "Gorstian", "min": 421.3, "min_sigma": 2.6, "max": 422.9, "max_sigma": 2.5},
    "homerian": { "name": "Homerian", "min": 422.9, "min_sigma": 2.5, "max": 426.2, "max_sigma": 2.4},
    "sheinwoodian": { "name": "Sheinwoodian", "min": 426.2, "min_sigma": 2.4, "max": 428.2, "max_sigma": 2.3},
    "telychian": { "name": "Telychian", "min": 428.2, "min_sigma": 2.3, "max": 436.1, "max_sigma": 1.9},
    "aeronian": { "name": "Aeronian", "min": 436.1, "min_sigma": 1.9, "max": 439, "max_sigma": 1.8},
    "rhuddanian": { "name": "Rhuddanian", "min": 439, "min_sigma": 1.8, "max": 443.7, "max_sigma": 1.5},
    "unnamed - 6": { "name": "Unnamed - 6", "min": 443.7, "min_sigma": 1.5, "max": 450.2, "max_sigma": 1.6},
    "unnamed - 5": { "name": "Unnamed - 5", "min": 450.2, "min_sigma": 1.6, "max": 460.9, "max_sigma": 1.6},
    "darriwilian": { "name": "Darriwilian", "min": 460.9, "min_sigma": 1.6, "max": 468.1, "max_sigma": 1.6},
    "unnamed - 3": { "name": "Unnamed - 3", "min": 468.1, "min_sigma": 1.6, "max": 471.8, "max_sigma": 1.6},
    "unnamed - 2": { "name": "Unnamed - 2", "min": 471.8, "min_sigma": 1.6, "max": 478.6, "max_sigma": 1.7},
    "tremadocian": { "name": "Tremadocian", "min": 478.6, "min_sigma": 1.7, "max": 488.3, "max_sigma": 1.7}
  }
};
